baseURL = 'https://seven-demo.supcat.cn/'
languageCode = 'en-us'
title = 'Seven的个人网站'

hasCJKLanguage = true
paginate = 18

disqusShortname = ""  # "seven-demo"

[outputs]
home = ["HTML", "Algolia"]

[outputFormats]
  [outputFormats.Algolia]
    baseName = 'algolia'
    isPlainText = true
    notAlternative = true
    mediaType = 'application/json'

[Params]
  description = "Seven Demo"
  
  enableToTop = false
  enableSearch = true
  enableComments = true

  [Params.home]
    # Customize the type of content to display up-to-date, 
    # and display all content with 'IsPage=true' if not.
    # eg: showContentTypes = ["posts", "blogs"]
    showContentTypes = []
    # Customize the type of content to recommended,
    # and recommend contents with 'is_recommend=true' if not.
    # eg: recommendedTypes = ["posts"]
    recommendedTypes = []

  description = "记录学习、生活的个人博客网站"
  [Params.hero]
    img = "/images/hero/hero.jpg"

  # App icon config
  [Params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Seven Demo"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "/favicon.svg"
    # Safari mask icon color
    iconColor = "#ffffff"
    # Android browser theme color
    themeColor = "#ffffff"

  # LOGO
  [Params.logo]
    # Image logo or Text logo
    # Recommended to set image as logo. (prefer)
    img = "/images/logo.svg"
    img_dark = "/images/logo-footer.svg"
    img_footer = "/images/logo-footer.svg"
    img_height = "" # eg: 64px
    footer_height = ""
    text = "Seven-Demo"
    textColor = "#50d71e"


  # Copyright 
  [Params.copyright]
    owner = "Seven"
    start_year = "2022"

  # Article Meta
  [Params.articleMeta]
    enableAuthor = false
    disableDate = false
    disableModifiedDate = false
    disableCountWords = false
    disableReadTime = false
    disableHero = false
    disableToc = false
  
  # Society
  [Params.society]
    bilibili = ""
    email = "linzhanqi123@gmail.com"
    facebook = ""
    github = "https://github.com/mrhelloboy/hugo-theme-seven-demo"
    instagram = ""
    pinterest = ""
    tiktok = ""
    twitter = ""
    weibo = ""
    youtube = ""
    zhihu = ""

  # Search-Algolia
  [Params.algolia]
    # Type of content. see: https://gohugo.io/content-management/types/
    type = ["posts"]
    # like pages variables. see: https://gohugo.io/variables/page/
    vars = ["title", "description", "permalink"]
    # Front Matter Variables. 
    # see: https://gohugo.io/content-management/front-matter/#front-matter-variables
    params = ["tags"]

    app_id = "995JRM5ZAU"
    api_key = "4a1095e4b8c96d2baee42d4c64b16afa"
    index = "hugo_theme_seven_demo"
    # see: https://www.algolia.com/doc/api-reference/widgets/snippet/js/#about
    snippet_attr = "description"
    # see: https://www.algolia.com/doc/api-reference/widgets/highlight/js/#examples
    highlight_attr = "title"
  
  # Comment - Waline
  # See: https://waline.js.org/en/
  [Params.waline]
    # https://waline.js.org/en/guide/features/pageview.html#use-alone
    alonePageview = false
    serverURL = "https://seven-demo.comment.supcat.cn/.netlify/functions/comment"
    lang = "en"
    reaction = true
    search = true
    comment = true
    pageview = true


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = false

  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
  

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[menu]
  [[menu.main]]
    name = "Doc"
    pre = ""
    url = "/doc/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    pre = "categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tags"
    url = "/tags/"
    weight = 4

[module]
  # It is recommended that Chinese users modify the proxy configuration
  # proxy = 'https://goproxy.cn,direct'
  # workspace = 'on'
  [[module.imports]]
    path = 'github.com/mrhelloboy/seven'
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
